CREATE TABLE PRIME_NUMBER_CHECK (
    SR_NO int NOT NULL AUTO_INCREMENT,
    INPUT_NUMBER varchar(255),
    RESULT varchar(255),
    PRIMARY KEY (SR_NO)
);

INSERT INTO PRIME_NUMBER_CHECK (INPUT_NUMBER,RESULT) VALUES(%s,%s);